---

- name: Install epel yum repository
  yum:
    name: epel-release
    state: present

- name: "Start package upgrade, excluding packages requiring a reboot"
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  # Can an update take as long as an hour?
  async: 3600
  # Don't wait for async task
  poll: 0
  # async job is always changed so ignore
  changed_when: false
  register: yum_package_update
  
- name: "Wait for yum_package_update async task"
  async_status:
    jid: "{{ yum_package_update.ansible_job_id }}"
  register: yum_package_update_result
  until: yum_package_update_result.finished
  retries: 60
  delay: 60

- name: "Start upgrade for packages requiring restart"
  yum:
    name: 'kernel*'
    state: latest
  # Can an update take as long as an hour?
  async: 3600
  # Don't wait for async task
  poll: 0
  # async job is always changed so ignore
  changed_when: false
  register: yum_reboot_update
  
- name: "Wait for yum_reboot_update async task"
  async_status:
    jid: "{{ yum_reboot_update.ansible_job_id }}"
  register: yum_reboot_update_result
  until: yum_reboot_update_result.finished
  retries: 60
  delay: 60

- name: An update that needs a reboot may require a manual reboot
  when:
    - not auto_reboot | bool
    - yum_reboot_update_result.changed
  fail:
    msg: "[REBOOT REQUIRED] New kernel install and auto_reboot is disabled"
    
- name: An update that needs a reboot requires an automated reboot
  when: 
    - auto_reboot | bool
    - yum_reboot_update_result.changed
  reboot:

