---

- name: Install epel yum repository
  yum:
    name: epel-release
    state: present

- name: "Start package upgrade, excluding packages requiring a reboot"
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  # Can an update take as long as an hour?
  async: 3600
  # Poll every 60 seconds to avoid ssh timeout
  poll: 60
  # Retry if connection goes down
  retries: 3

- name: "Start upgrade for packages requiring reboot"
  yum:
    name: 'kernel*'
    state: latest
  # Can an update take as long as an hour?
  async: 3600
  # Poll every 60 seconds to avoid ssh timeout
  poll: 60
  # Retry if connection goes down
  retries: 3
  register: yum_reboot_update_result

- name: An update that needs a reboot may require a manual reboot
  when:
    - not auto_reboot | bool
    - yum_reboot_update_result.changed
  fail:
    msg: "[REBOOT REQUIRED] New kernel install and auto_reboot is disabled"
    
- name: An update that needs a reboot requires an automated reboot
  when: 
    - auto_reboot | bool
    - yum_reboot_update_result.changed
  reboot:

